name: Release R CMD check

on: push

jobs:
  checkPublish:
    runs-on: ubuntu-20.04
    container: bioconductor/bioconductor_docker:RELEASE_3_13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Set env vars
        run: |
            echo "version-name=RELEASE_3_13" >> $GITHUB_ENV

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ runner.os }}-r-${{ env.version-name }}-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ env.version-name }}-

      - name: Install Dependencies
        run: |
          options(repos = c(CRAN = "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"))
          remotes::install_local(dependencies = TRUE, repos = AnVIL::repositories(), build_vignettes = TRUE, upgrade = TRUE)
          BiocManager::install(c("rcmdcheck", "pkgdown"), update = TRUE, ask = FALSE)
        shell: Rscript {0}

      - name: System dependencies
        run: |
          pip install ghp-import

      - name: Check Package
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c('--no-manual'), error_on = 'error', check_dir = 'check')
        shell: Rscript {0}

      - name: Build pkgdown
        run: |
           PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_site(".")'

      - name: Install deploy dependencies
        run: |
          apt-get update
          apt-get -y install rsync

      - name: Deploy to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.


