name: Test Conda Build Docker
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v1
      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          repository: waldronlab/cBioPortalData
          # don't push, since this is a test
          push: false
          dockerfile: inst/docker/Dockerfile
