name: Build Conda Docker

on:
  push:
    branches:
      - devel
    paths:
      - DESCRIPTION

jobs:
  conda:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v3
      -
        name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          # don't push, since this is a test
          push: false
          file: inst/docker/Dockerfile
