name: Update to cBio Portal API

on: workflow_dispatch

jobs:
  apiUpdate:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: Rscript -e "install.packages('digest')"

      - name: Download API and write MD5
        run: Rscript -e "source('./inst/scripts/update_api-docs.R')"

      - name: Commit changes
        if: ${{ success() }}
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
          git commit -am "Update to API"

      - name: Push action
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

