name: Update to cBio Portal API

on: workflow_dispatch

jobs:
  apiUpdate:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: Rscript -e "install.packages('digest')"

      - name: Add safe directory
        run: git config --global --add safe.directory /__w/cBioPortalData/cBioPortalData

      - name: Download API and write MD5
        run: Rscript -e "source('./inst/scripts/update_api-docs.R')"

      - name: Commit changes
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update API'

      - name: Push action
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

